--全局常量
_G.M23M = {
	RPC_NAMESPACE = "M23M",

	MOD_LOG_HEADER = "[ROOM] [INFO]",
	RPC_LOG_HEADER = "[ROOM] [RPC] ",
	MOD_ERROR_HEADER = "[ROOM] [ERROR] ",
	MOD_WARNING_HEADER = "[ROOM] [WARNING] ",
	MOD_DEBUG_HEADER = "[ROOM] [DEBUG] ",

	ROOM_DEFS = {},
	TOO_LARGE_ROOM_SIZE = 1280, --房间过大时的最大尺寸
}