--Actions
STRINGS.ACTIONS.AGCW_POPUP_SCREEN = "查看"
STRINGS.ACTIONS.GENESIS_SHOW_UI_OVERRIDE = {	--AddAction接口会覆盖STRINGS.ACTIONS.AGCW_POPUP_SCREEN，因此需要人为重新覆盖回去
	GENERIC = "查看",
	PLOW_TILE_SELECT = "规划地块",
}

--自动开垦机
STRINGS.NAMES.AGCW_FARM_PLOW_MACHINE_ITEM = "便携式自动开垦机"
STRINGS.RECIPE_DESC.AGCW_FARM_PLOW_MACHINE_ITEM = ""
STRINGS.CHARACTERS.GENERIC.DESCRIBE.AGCW_FARM_PLOW_MACHINE_ITEM = ""

STRINGS.NAMES.AGCW_FARM_PLOW_MACHINE = "自动开垦机"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.AGCW_FARM_PLOW_MACHINE = ""

--测试电源
STRINGS.NAMES.AGCW_POWER_SOURCE = "测试电源"
STRINGS.RECIPE_DESC.AGCW_POWER_SOURCE = ""
STRINGS.CHARACTERS.GENERIC.DESCRIBE.AGCW_POWER_SOURCE = ""

--测试用电器
STRINGS.NAMES.AGCW_POWER_APP = "测试用电器"
STRINGS.RECIPE_DESC.AGCW_POWER_APP = ""
STRINGS.CHARACTERS.GENERIC.DESCRIBE.AGCW_POWER_APP = ""