--Actions
STRINGS.ACTIONS.M23M_POPUP_SCREEN = "Check"
STRINGS.ACTIONS.M23M_SHOW_UI_OVERRIDE = {	--AddAction接口会覆盖STRINGS.ACTIONS.M23M_POPUP_SCREEN，因此需要人为重新覆盖回去
	GENERIC = "Check",
}

-- Rooms
STRINGS.M23M_ROOMS = {
	NO_NAME = {
		NAME = "Room without name",
		DESC = "Mod has registered the room type, but has not configured a description for it."
	},
	NONE = {
		NAME = "Normal Room/ Not Room",
		DESC = "Ordinary and unremarkable."
	},
}

--测试电源
STRINGS.NAMES.M23M_POWER_SOURCE = "测试电源"
STRINGS.RECIPE_DESC.M23M_POWER_SOURCE = ""
STRINGS.CHARACTERS.GENERIC.DESCRIBE.M23M_POWER_SOURCE = ""

--测试用电器
STRINGS.NAMES.M23M_POWER_APP = "测试用电器"
STRINGS.RECIPE_DESC.M23M_POWER_APP = ""
STRINGS.CHARACTERS.GENERIC.DESCRIBE.M23M_POWER_APP = ""

--补充没有直接对应名称的物品的名称
STRINGS.NAMES.PORTABLECOOKPOT = STRINGS.NAMES.PORTABLECOOKPOT_ITEM
STRINGS.NAMES.PORTABLEBLENDER = STRINGS.NAMES.PORTABLEBLENDER_ITEM
STRINGS.NAMES.PORTABLESPICER = STRINGS.NAMES.PORTABLESPICER_ITEM